lkl: Introduce flags for reserve_bootmem()
A similar tree-wide change was done in 72a7fe3967dbf86cb34e24fbf1d957fe24d2f246.

Fix:
  CC      arch/lkl/kernel/mem.o
arch/lkl/kernel/mem.c: In function ‘mem_init_0’:
arch/lkl/kernel/mem.c:311: error: too few arguments to function ‘reserve_bootmem’