lkl: add atomic_cmpxchg - (call the local generic implementation - no SMP)
The build will fail on SMP because of #include <asm-generic/cmpxchg.h>.
This must be fixed by using um/ techniques.

Fix:
  CC      init/main.o
In file included from include/linux/mempolicy.h:62,
   from init/main.c:51:
   include/linux/pagemap.h: In function ‘page_freeze_refs’:
   include/linux/pagemap.h:199: error: implicit declaration of function ‘atomic_cmpxchg’