lkl: declare strlen and strchr only if those symbols are not defined
Libc can implement them as #defines and sometimes (as on my machines) it does.

Example: with CFGLAS+=-O
  strchr("mimi", 'm')
was defined as
  (__extension__ (__builtin_constant_p ('m') && !__builtin_constant_p ("mimi") &&
     ('m') == '\0' ? (char *) __rawmemchr ("mimi", 'm') : __builtin_strchr("mimi", 'm')));

Fix:
gcc -Wall -g -O  -Iinclude -Iposix/include vfs.c posix/vmlinux posix/lkl.a -lpthread -o vfs.posix
In file included from vfs.c:7:
include/asm/lkl.h:112: error: expected identifier or ‘(’ before ‘__extension__’
include/asm/lkl.h:113: error: expected identifier or ‘(’ before ‘__extension__’