lkl: add missing __alloc_zeroed_user_highpage
     I don't know why the default implementation does not set __GFP_ZERO
     and archs need to implicitly set this.
     The tree-wide change was done in 769848c03895b63e5662eb7e4ec8c4866f7d0183.

     Fix:
       CC      init/main.o
       In file included from include/linux/pagemap.h:10,
                        from include/linux/mempolicy.h:62,
                        from init/main.c:51:
         include/linux/highmem.h: In function ‘alloc_zeroed_user_highpage_movable’:
         include/linux/highmem.h:117: error: implicit declaration of function ‘__alloc_zeroed_user_highpage’