lkl: add __init_begin and __init_end
These symbols were removed with some other ones by Tavi to add
mingw support in 0fd835e356c66ccb33818f4407520e1f9adefb8c.
Will need to see if mingw breaks now ...

Fix:
  gcc -Wall -g -O0  -Iinclude -Iposix/include vfs.c posix/vmlinux posix/lkl.a -lpthread -o vfs.posix
  posix/vmlinux: In function `mem_init':
  arch/lkl/kernel/mem.c:345: undefined reference to `__init_begin'
  arch/lkl/kernel/mem.c:345: undefined reference to `__init_end'