lkl: take init_fs to saner place
  init_fs was moved in the rest of the kernel from arch files into fs/namei.c
  See 18d8fda7c3c9439be04d7ea2e82da2513b121acb for details.

      CC      arch/lkl/kernel/setup.o
  arch/lkl/kernel/setup.c:19: error: static declaration of ‘init_fs’ follows non-static declaration
  include/linux/init_task.h:15: note: previous declaration of ‘init_fs’ was here
  arch/lkl/kernel/setup.c:19: error: ‘INIT_FS’ undeclared here (not in a function)