lkl: update scatterlist: Change table chaining layout
    Update the structure as expected by the rest of the kernel.
    A similar update was done in 18dabf473e15850c0dbc8ff13ac1e2806d542c15.

    Change the page member of the scatterlist structure to be an unsigned
    long, and encode more stuff in the lower bits:
    - Bits 0 and 1 zero: this is a normal sg entry. Next sg entry is located
      at sg + 1.
    - Bit 0 set: this is a chain entry, the next real entry is at ->page_link
      with the two low bits masked off.
    - Bit 1 set: this is the final entry in the sg entry. sg_next() will return
      NULL when passed such an entry.

    It's thus important that sg table users use the proper accessors to get
    and set the page member.

     Fix:
       CC      init/do_mounts.o
       In file included from include/linux/sunrpc/xdr.h:14,
                 from include/linux/sunrpc/sched.h:17,
                 from include/linux/sunrpc/auth.h:14,
                 from include/linux/nfs_fs.h:51,
                 from init/do_mounts.c:18:
        include/linux/scatterlist.h: In function ‘sg_assign_page’:
        include/linux/scatterlist.h:57: error: ‘struct scatterlist’ has no member named ‘page_link’
        include/linux/scatterlist.h:68: error: ‘struct scatterlist’ has no member named ‘page_link’
        include/linux/scatterlist.h: In function ‘sg_page’:
        include/linux/scatterlist.h:99: error: ‘struct scatterlist’ has no member named ‘page_link’
        include/linux/scatterlist.h: In function ‘sg_chain’:
        include/linux/scatterlist.h:148: error: ‘struct scatterlist’ has no member named ‘page_link’
        include/linux/scatterlist.h: In function ‘sg_mark_end’:
        include/linux/scatterlist.h:168: error: ‘struct scatterlist’ has no member named ‘page_link’
        include/linux/scatterlist.h:169: error: ‘struct scatterlist’ has no member named ‘page_link’