lkl: remove PTRACE_SYSEMU support from lkl
TIF_SYSCALL_EMU is an x86 thinggy.
It's also used by um, so we should check how they support it.

Fix:
  kernel/ptrace.c: In function ‘ptrace_resume’:
  kernel/ptrace.c:410: error: ‘PTRACE_SYSEMU’ undeclared (first use in this function)